---
abstract: unknown
author:
  - 'Le Garff Yoann <pe.weeble@yahoo.fr>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CTM-ReadEM
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  DBI: '0'
  Exporter: '0'
  Hash::Util: '0'
  POSIX: '0'
  Time::Local: '0'
version: '0.173'
